#logging:
#  config: src/main/resources/logback-test.xml

logging:
  level: {root: info}


server:
  port: 80

spring:
  data:
    elasticsearch:
      cluster-nodes: 192.168.0.90:9200
      repositories:
        enabled: true

    hbase:
      quorum: node2
      clientPort: 2181
  elasticsearch:
    jest:
      uris:
      - http://192.168.0.90:9200
      read-timeout: 500000

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: monetware
    url: jdbc:mysql://localhost:13306/ringspider3?characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置